{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.global.namespace }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.api.service.name }}
            port:
              number: {{ .Values.api.service.port }}
      - path: /jupyter(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.jupyter.service.name }}
            port:
              number: {{ .Values.jupyter.service.port }}
{{- end }}